level = [
    "                                                                                                                          ",
    "P                                                                                                                        ",
    "P        PPPPP                                                                                                          ",
    "P                                                                                                                        ",
    "P                    PPPPPPPP                                                                                           ",
    "P                                          PPPP                                                                         ",
    "P                                                        PPPPPPPPPPPP                                                  ",
    "P                                                                                                                        ",
    "P              PPPP                                                              PPPPPP                                ",
    "P                                                                                                                        ",
    "P                                PPPPPPPPPP                                                    PPPPPP                  ",
    "P                                                                     PPPP                                              ",
    "P                                                                                                                        ",
    "P    PPPPPPPPPPPP                                                                                      PPPPPPPPPPPP     ",
    "P                                                                                                                        ",
    "P                          PPPPPP                    PPPPPP                  PPPPPPPPPP                                ",
    "P                                                                                                                        ",
    "P                                        PPPP                                                    PPPP                  ",
    "P                                                                                                                        ",
    "P         PPPPPPPPPPPP                                        PPPPPPPPPPPP                                             ",
    "P                                                                                                                        ",
    "P                                    PPPP                                             PPPP                             ",
    "P  "
    "P                                                                                                                      ",
    "P                                                                                                                      ",
    "PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP",
]