level = [
        "                                         ",
        "                                         ",
        "                                         ",
        "                                         ",
        "                                         ",
        "                                         ",
        "                                         ",
        "                                         ",
        "                                         ",
        "                                         ",
        "                                         ",
        "                                         ",
        "                                         ",
        "                                         ",
        "                                         ",
        "                                         ",
        "PPPP                                     ",
        "                                         ",
        "           PPPP                   PPPP   ",
        "                                         ",
        "                                         ",
        "              PPPPP                      ",
        "                           PPPP          ",
        "PPPPP PPPPPPPPPPPPPPP PPPPPPPPP PPPPPPPPPP"
    ]